# **Student Chance of Admission Prediction in Higher Studies**

Predict the chances of admission of a student to a University fro Graduate program based on different parameters such as:

GRE Scores (290 to 340) TOEFL Scores (92 to 120) University Rating (1 to 5) Statement of Purpose (1 to 5) Letter of Recommendation Strength (1 to 5) Undergraduate CGPA (6.8 to 9.92) Research Experience (0 or 1) Chance of Admit (0.34 to 0.97)

Dataset : https://github.com/ybifoundation/Dataset/raw/main/Admission%20Chance.csv

In [1]:
import pandas as pd

In [2]:
admission=pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Admission%20Chance.csv')

In [3]:
admission.head()

,Serial No,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [4]:
admission.columns

Index(['Serial No', 'GRE Score', 'TOEFL Score', 'University Rating', ' SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [5]:
y=admission['Chance of Admit ']
x=admission[['Serial No', 'GRE Score', 'TOEFL Score', 'University Rating', ' SOP',
       'LOR ', 'CGPA', 'Research']]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7, random_state=2529)
x_train

,Serial No,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
381,382,319,105,3,3.0,3.5,8.67,1
48,49,321,110,3,3.5,5.0,8.85,1
20,21,312,107,3,3.0,2.0,7.90,1
296,297,310,107,3,3.5,3.5,8.67,0
373,374,321,109,3,3.0,3.0,8.54,1
...,...,...,...,...,...,...,...,...
72,73,321,111,5,5.0,5.0,9.45,1
228,229,318,112,3,4.0,3.5,8.67,0
316,317,298,101,2,1.5,2.0,7.86,0
50,51,313,98,3,2.5,4.5,8.30,1
352,353,303,100,2,3.0,3.5,8.06,1

In [9]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [10]:
model.fit(x_train,y_train)

LinearRegression()

In [11]:
y_pred=model.predict(x_test)

In [12]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error

In [13]:
mean_absolute_error(y_test, y_pred)

0.04308714723355852

In [14]:
mean_absolute_percentage_error(y_test, y_pred)

0.074004372761339

In [15]:
mean_squared_error(y_test, y_pred)

0.003922607781791493