# **Credit Default Prediction**

The data set consists of 2000 samples from each of two categories. 
Five variables are
1. Income	
2. Age	
3. Loan	
4. Loan to Income (engineered feature)
5. Default

Dataset: https://github.com/ybifoundation/Dataset/raw/main/Credit%20Default.csv

In [15]:
import pandas as pd

In [16]:
credit= pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Credit%20Default.csv')

In [17]:
credit

           Income        Age         Loan  Loan to Income  Default
0     66155.92510  59.017015  8106.532131        0.122537        0
1     34415.15397  48.117153  6564.745018        0.190752        0
2     57317.17006  63.108049  8020.953296        0.139940        0
3     42709.53420  45.751972  6103.642260        0.142911        0
4     66952.68885  18.584336  8770.099235        0.130990        1
...           ...        ...          ...             ...      ...
1995  59221.04487  48.518179  1926.729397        0.032535        0
1996  69516.12757  23.162104  3503.176156        0.050394        0
1997  44311.44926  28.017167  5522.786693        0.124636        1
1998  43756.05660  63.971796  1622.722598        0.037086        0
1999  69436.57955  56.152617  7378.833599        0.106267        0

[2000 rows x 5 columns]

In [18]:
credit.columns

Index(['Income', 'Age', 'Loan', 'Loan to Income', 'Default'], dtype='object')

In [19]:
y=credit['Default']

In [20]:
x=credit[['Income', 'Age', 'Loan', 'Loan to Income']]

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=2529)

In [22]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [23]:
model.fit(x_train,y_train)

LogisticRegression()

In [24]:
y_pred=model.predict(x_test)

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [27]:
accuracy_score(y_test,y_pred)

0.908

In [28]:
confusion_matrix(y_test,y_pred)

array([[424,   9],
       [ 37,  30]])

In [29]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95       433
           1       0.77      0.45      0.57        67

    accuracy                           0.91       500
   macro avg       0.84      0.71      0.76       500
weighted avg       0.90      0.91      0.90       500